name: Bug Report
description: Report a bug in @careagent/provider-core
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `careagent init`
        2. Enter credentials...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "@careagent/provider-core version"
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "22.12.0"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04 / macOS 14 / etc."
    validations:
      required: true
